### ISSUE TITLE
Unified build repository for F4MP.

### ISSUE THREAD

**Issue by blipvert** [F4MP/F4MP#4]
As a code contributor, I want a single, unified repository for all F4MP sources, and a single build process.

#### Requirements
1. `F4MP.git` must be the unified repository in order to preserve the stars.
2. CMake shall be used for the build process.

#### Tasks
- [x] Current state of the `master` branch is preserved in a new branch called `legacy` in the `F4MP` repository.
- [x] A new branch called `unified` is created for the remainder of the work done in this story.
- [x] `F4MPServer` and `F4MPClient` repositories are added as submodules `server` and `client`, respectively.
- [x] Top-level `CMakeLists.txt` is created for the entire build process.
- [x] Legacy code not part of the build is deleted from this branch.
